### ISSUE TITLE
Bug datatype management in OperatorFunction of torch_support.py

### ISSUE THREAD

**Issue by schoonhovenrichard** [ahendriksen/tomosipo#15]
**Issue**
Using 64-bit floats in OperatorFunction leads to output buffer initialized with 64-bits:
https://github.com/ahendriksen/tomosipo/blob/3477a07db863349b650769e8d296c5cd5cec9f90/tomosipo/torch_support.py#L32

In forward pass, Tomosipo converts input to 32-bit floats as expected. However, since the output of the application of the operator is written to the output buffer (with 64-bit datatype), this leads to an error:
https://github.com/ahendriksen/tomosipo/blob/3477a07db863349b650769e8d296c5cd5cec9f90/tomosipo/torch_support.py#L35

**Fix**
Force output buffer to be 32-bit float since ASTRA works always expects 32-bit floats anyway.
`out = input.new_empty(B, *operator.range_shape, dtype=torch.float32)`

This is also forced in Tomosipo since it is always converted:
https://github.com/ahendriksen/tomosipo/blob/3477a07db863349b650769e8d296c5cd5cec9f90/tomosipo/links/torch.py#L54

**Comment by D1rk123** [comment]
This was fixed in pull request #16.
