### ISSUE TITLE
Adjoint of operator with autograd

### ISSUE THREAD

**Issue by Evidlo** [ahendriksen/tomosipo#21]
Is there a way to access the adjoint of an operator when autograd is turned on?

``` python
#!/usr/bin/env python3

import tomosipo as ts
import torch as t
import numpy as np

shape = (32, 32, 32)

vg = ts.volume(shape=shape, size=(1, 1, 1))
pg = ts.parallel(angles=32, shape=(48, 48), size=(1.5, 1.5))

A = ts.operator(vg, pg)
A_torch = ts.torch_support.to_autograd(A)

print(A.T)
print(A_torch.T)
```

```
>>> %run transpose_autograd.py
<tomosipo.Operator.BackprojectionOperator object at 0x7f5b1c302b20>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/research/carruthers/transpose_autograd.py:16
     13 A_torch = ts.torch_support.to_autograd(A)
     15 print(A.T)
---> 16 print(A_torch.T)

AttributeError: 'function' object has no attribute 'T'
```

**Comment by ahendriksen** [comment]
Something like this? 

A = ts.operator(vg, pg) 
A_torch = ts.torch_support.to_autograd(A)
AT_torch = ts.torch_support.to_autograd(A.T)

On Thu, Sep 21, 2023, at 6:48 PM, Evan Widloski wrote:
> 
> 
> Is there a way to access the adjoint of an operator when autograd is turned on?
> 
> #!/usr/bin/env python3
> 
> import tomosipo as ts
> import torch as t
> import numpy as np
> 
> shape = (32, 32, 32)
> 
> vg = ts.volume(shape=shape, size=(1, 1, 1))
> pg = ts.parallel(angles=32, shape=(48, 48), size=(1.5, 1.5))
> 
> A = ts.operator(vg, pg)
> A_torch = ts.torch_support.to_autograd(A)
> 
> print(A.T)
> print(A_torch.T)
> `>>> %run transpose_autograd.py
> <tomosipo.Operator.BackprojectionOperator object at 0x7f5b1c302b20>
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> File ~/research/carruthers/transpose_autograd.py:16
>      13 A_torch = ts.torch_support.to_autograd(A)
>      15 print(A.T)
> ---> 16 print(A_torch.T)
> 
> AttributeError: 'function' object has no attribute 'T'
`

**Comment by Evidlo** [comment]
Thanks, that works!
