### ISSUE TITLE
torch autograd capabilities

### ISSUE THREAD

**Issue by QuantPrincess** [ahendriksen/tomosipo#32]
Are forward projections compatible with gradient tracking/torch.autograd? I seem to be running into some issues with tracking gradients after performing the forward projections, and was wondering if there is anything special I need to do?

**Comment by D1rk123** [comment]
The standard tomosipo operators are not compatible with Pytorch autograd. However, you can create an autograd-compatible operator using the to_autograd function. The documentation for this function can be found below:
https://aahendriksen.gitlab.io/tomosipo/ref/tomosipo.torch_support.html#tomosipo.torch_support.to_autograd

**Comment by QuantPrincess** [comment]
Thanks so much!
