### ISSUE TITLE
Cone beam projector scaling issue ? 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [ahendriksen/tomosipo#35]
I am trying to set up a cone beam reconstruction using tomoSIPO. I was getting artifacts which looked like overlapping versions of the true volume but rotated by a bit. 

I went back to a simpler case; setting up a phantom forward projector and I see some unexpected behavior. 

Here is the code. 

#########################################

#180mm X 180mm detector 

det_row = 150
det_col  = 150 
num_angles = 32 

det_pix_size = 1.2 #mm
src_orig_dist = 20 #mm
orig_det_dist = 100 

#1.5mm X 1.5mm X 1.5mm sized volume 

vox_size = 0.2 #mm
n_vox_x = 75 
n_vox_y = 75 
n_vox_z = 90 

density=1.0

#Simple square phantom of size 20 X 20 with values of density 

obj = np.zeros((n_vox_z, n_vox_x, n_vox_y)).astype(np.float32)
obj[n_vox_z//2,n_vox_x//2-10:n_vox_x//2+10,n_vox_y//2-10:n_vox_y//2+10]=density

obj = torch.from_numpy(obj).to(device)

angles = np.linspace(0, 2 * np.pi, num_angles, False)

sdd = src_orig_dist + orig_det_dist #Source to detector distance 

vol_geom = ts.volume(shape=(n_vox_z, n_vox_x, n_vox_y), size=(vox_size, vox_size, vox_size))
proj_geom = ts.cone(angles=angles,size=(det_pix_size,det_pix_size),shape=(det_row,det_col),src_orig_dist=src_orig,src_det_dist=sdd)
A = ts.operator(vol_geom, proj_geom)
f = to_autograd(A)
projs = f(obj)

#########################################

I would expect a square shaped object (when not rotated) to project to values which are like 20*0 .2*1.0 = 4  (num_voxels*side_length*density); and the footprint to occupy roughly (20*0.2*6/1.2) ~ 20 detector pixels (num_voxels*side_length*geometric_mag/det_pixel_size). 

However, when I inspect "projs" above, these number are instead  0.0424 and 40 pixels respectively. 

Not sure if I am missing something or there is some scaling issue with tomoSIPO's cone beam projectors.

**Comment by D1rk123** [comment]
Sorry for not replying, and thank you for sharing the solution you found.
