### ISSUE TITLE
tomosipo.parallel standard is 2pi

### ISSUE THREAD

**Issue by MJLagerwerf** [ahendriksen/tomosipo#4]
Calling 
`tomosipo.parallel(angles=180, shape=(1, 384))`

Gives a parallel beam geometry over the full circle instead of the standard half circle

**Comment by ahendriksen** [comment]
That was the default previously. This has been changed in the current develop branch. 

Please Install With

'Pip install —upgrade git+https://github.com/ahendriksen/tomosipo.git@develop` 

I would recommend using the develop branch. Many defaults are improved and it includes the ability to directly use ASTRA operations on numpy arrays and Pytorch tensors.

**Comment by ahendriksen** [comment]
I see that the documentation has not yet been updated in the develop branch. This should still be done.

**Comment by ahendriksen** [comment]
Fixed in b1cd9bc1def9a37dfd995ad03df2164526472512
